module.exports = [
  "achilles ",
  "acl ",
  "bicep ",
  "coronavirus ",
  "covid ",
  "covid-19 ",
  "injured ",
  "injuries ",
  "injury ",
  "isolation ",
  "mandatory isolation ",
  "meniscus ",
  "out for ",
  "out indefinitely ",
  "test positive ",
  "tested positive ",
  "tests positive ",
  "quarantine ",
  "season-ended ",
  "season-ending ",
  "suffered ",
  "surgery ",
  "suspended ",
  "suspension ",
  "symptoms ",
  "tests ",
  "core muscle ",
  " tricep ",
  " torn ",
  "contusion ",
  "hamstring ",
  " hip ",
  "pelvis ",
  "pelvic ",
  " spine ",
  " spinal ",
  "concussed ",
  "concussion ",
  "concussions ",
  "upper body ",
  "upper-body ",
  "lower body ",
  "lower-body ",
  " mri ",
  " groin ",
  " strain ",
  " strained ",
  " strains ",
  " calf ",
  "lacerate ",
  "lacerated ",
  "lacerates ",
  "fracture ",
  "fractured ",
  "fractures ",
  "rupture ",
  "ruptured ",
  "ruptures ",
  " mcl ",
  " lcl ",
  " bone ",
  " wrist ",
  " broken ",
  " finger ",
  " elbow ",
  " shoulder ",
  " ankle ",
  " toe ",
  " quad ",
  "quadricep ",
  "quadriceps ",
  "broken rib ",
  "broken ribs ",
  "significant knee",
  "soft tissue",
  "soft-tissue",
  "metacarpal ",
  "tibia ",
  "fibula ",
  " broken ",
  "pectoral ",
  "labrum ",
  "rotator cuff",
  "turf toe",
  "plantar fasciitis",
  "end of season",
];
