module.exports = [
  " nursing ",
  "not practicing",
  " prevent ",
  "since ",
  "ever since",
  " squad ",
  "if ",
  "doesn't ",
  "does not",
  " takeaways ",
  " breakdown ",
  "break-down",
  "break down",
  "dealing with",
  ". should ",
  " off of",
  "recovered from",
  "back from",
  "used to",
  "first game since",
  "non covid",
  "non-covid",
  "injury report",
  "won't practice",
  "will not practice",
  "day to day",
  "day-to-day",
  "returns from",
  " could return",
  " will return",
  " will not",
  "not concerned",
  "not concerning",
  " reserve list ",
  " missed ",
  " waived ",
  " released ",
  " actually ",
  " hopefully ",
  " opinion ",
  " camp ",
  " already ",
  " waived-injured ",
  " league-wide ",
  " waivers ",
  "waiver",
  "reserve",
  " reminder ",
  " p.m. ",
  " waivers ",
  " reminder ",
  " whether ",
  " status ",
  " rt @ ",
  " back practicing",
  " protocols ",
  " roster moves ",
  " covid testing ",
  " pandemic ",
  " will be available ",
  " signed ",
];
